spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: num
      password: gncngncn11
      connection-test-query: SELECT 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
